apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasknode
  template:
    metadata:
      labels:
        app: flasknode
    spec:
      containers:
      - name: flasknode
        image: in-che.icr.io/helloworld-ibm/ibm
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
